name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  setup:

    name: Dependencies

    strategy:
        matrix:
            os: ['ubuntu-20.04', 'windows-latest']
            php: ['7.4']

    env:
        extensions: psr, phalcon
        key: extensions-cache
        tools: pecl, phpcs, phpstan

    runs-on: ${{ matrix.os }}

    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup cache environment
        id: extcache
        uses: shivammathur/cache-extensions@v1
        with:
          php-version: ${{ matrix.php }}
          extensions: ${{ env.extensions }}
          key: ${{ env.key }}-${{ matrix.os }}-${{ matrix.php }}-v1

      - name: Cache extensions
        uses: actions/cache@v2
        with:
          path: ${{ steps.extcache.outputs.dir }}
          key: ${{ steps.extcache.outputs.key }}
          restore-keys: ${{ steps.extcache.outputs.key }}

      - name: Get composer cache directory
        id: composercache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ${{ steps.composercache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.json') }}
          restore-keys: ${{ runner.os }}-composer-

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
            coverage: none
            php-version: ${{ matrix.php }}
            tools: ${{ env.tools }}
            extensions: ${{ env.extensions }}

      - name: Install dependencies
        run: composer install --prefer-dist

  phpstan:

    name: Static Analysis

    strategy:
        matrix:
            os: ['ubuntu-20.04', 'windows-latest']
            php: ['7.4']

    env:
        extensions: psr, phalcon
        key: extensions-cache
        tools: pecl, phpcs, phpstan

    runs-on: ${{ matrix.os }}

    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup cache environment
        id: extcache
        uses: shivammathur/cache-extensions@v1
        with:
          php-version: ${{ matrix.php }}
          extensions: ${{ env.extensions }}
          key: ${{ env.key }}-${{ matrix.os }}-${{ matrix.php }}-v1

      - name: Cache extensions
        uses: actions/cache@v2
        with:
          path: ${{ steps.extcache.outputs.dir }}
          key: ${{ steps.extcache.outputs.key }}
          restore-keys: ${{ steps.extcache.outputs.key }}

      - name: Get composer cache directory
        id: composercache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ${{ steps.composercache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.json') }}
          restore-keys: ${{ runner.os }}-composer-

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
            coverage: none
            php-version: ${{ matrix.php }}
            tools: ${{ env.tools }}
            extensions: ${{ env.extensions }}

      - name: Install dependencies
        run: composer install --prefer-dist

      - name: Static Analysis
        run: phpstan analyse

  phpcs:

    name: Code Styling

    strategy:
        matrix:
            os: ['ubuntu-20.04', 'windows-latest']
            php: ['7.4']

    env:
        extensions: psr, phalcon
        key: extensions-cache
        tools: pecl, phpcs, phpstan

    runs-on: ${{ matrix.os }}

    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup cache environment
        id: extcache
        uses: shivammathur/cache-extensions@v1
        with:
          php-version: ${{ matrix.php }}
          extensions: ${{ env.extensions }}
          key: ${{ env.key }}-${{ matrix.os }}-${{ matrix.php }}-v1

      - name: Cache extensions
        uses: actions/cache@v2
        with:
          path: ${{ steps.extcache.outputs.dir }}
          key: ${{ steps.extcache.outputs.key }}
          restore-keys: ${{ steps.extcache.outputs.key }}

      - name: Get composer cache directory
        id: composercache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ${{ steps.composercache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.json') }}
          restore-keys: ${{ runner.os }}-composer-

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
            coverage: none
            php-version: ${{ matrix.php }}
            tools: ${{ env.tools }}
            extensions: ${{ env.extensions }}

      - name: Install dependencies
        run: composer install --prefer-dist

      - name: Code Styling
        run: phpstan analyse

