name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    name: PHP ${{ matrix.php }} on ${{ matrix.os }}
    env:
        extensions: psr, phalcon-4.0.6
        key: extensions-cache-psr-phalcon-4.0.6
        tools: pecl, phpcs, phpstan
    runs-on: ${{ matrix.os }}
    strategy:
        matrix:
            os: ['ubuntu-20.04']
            php: ['7.4']

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup cache environment
        id: extcache
        uses: shivammathur/cache-extensions@v1
        with:
          php-version: ${{ matrix.php }}
          extensions: ${{ env.extensions }}
          key: ${{ env.key }}

      - name: Cache extensions
        uses: actions/cache@v2
        with:
          path: ${{ steps.extcache.outputs.dir }}
          key: ${{ steps.extcache.outputs.key }}
          restore-keys: ${{ steps.extcache.outputs.key }}

      - name: Get composer cache directory
        id: composercache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ${{ steps.composercache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.json') }}
          restore-keys: ${{ runner.os }}-composer-

      - name: Install dependencies
        run: composer install --prefer-dist

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
            coverage: none
            php-version: ${{ matrix.php }}
            tools: ${{ env.tools }}
            extensions: ${{ env.extensions }}

      - name: Static Analysis
        run: phpstan analyse

      - name: Code Styling
        run: phpstan analyse
